---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-devopsbyexample-io
  namespace: staging
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: grafana.devopsbyexample.io
  dnsNames:
  - grafana.devopsbyexample.io
  - www.grafana.devopsbyexample.io
  secretName: grafana-devopsbyexample-io-key-pair
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: devopsbyexample-io-ca
    kind: ClusterIssuer
    group: cert-manager.io
