---
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: production
spec:
  serviceAccountName: foo
  securityContext:
    fsGroup: 1002
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
