---
controller:
  ingressClassResource: 
    name: external-nginx
  watchIngressWithoutClass: true
  extraArgs:
    ingress-class: external-nginx
  admissionWebhooks:
    enabled: false
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
