---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: monitoring
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: me@antonputra.com
    privateKeySecretRef:
      name: letsencrypt-prod-key-pair
    solvers:
    - http01:
        ingress:
          class:  external-nginx
